### ISSUE TITLE
Log-In page and "API":"AUTH" to none

### ISSUE THREAD

**Issue by buster39** [RD17/ambar#39]
Hi!

Seems like a possible duplicate to #28. 

After registering an account i wanted to switch the login off. So that that no authentication is needed to reach the search page. That is my goal ... Should be possible with "auth" to "none" in the config file.

But i still get the login page when connecting to the root url.

Thank you!

**Comment by sochix** [comment]
Hi @buster39 , it was a bug. We just ignore `auth` setting in `config.json`. We fixed it in 0.10.0 release. Please run `sudo ./ambar.py reset. && sudo ./ambar.py update`

**Comment by sochix** [comment]
@buster39 is your issue solved?

**Comment by giulianogiuffrida** [comment]
Hi, I have the same issue with the newest version.

**Comment by buster39** [comment]
Sorry for answering late - no, not solved. Do you need any logs or similar?

**Comment by sochix** [comment]
~~Hi @buster39 and @sesshoumaru80 ! Can you please post here your `config.json` and result of `GET http://AMBAR_IP_ADDRESS/api/`~~

Found problem in dockerfile, will fix it

**Comment by buster39** [comment]
seems to work - thank you very much!

**Comment by sochix** [comment]
NICE!
